# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Your awesome title
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# twitter_username: jekyllrb
# github_username:  jekyll

logo: "/assets/images/luke_theme_logo_trimmed.jpeg"
logo_alt: "Luke theme's logo"

read_more_text: "詳細はこちら"

header_links:
  - name: "Home"
    url: "/"
  - name: "Products"
    url: "/products/"
  - name: "News"
    url: "/news/"
  - name: "About us"
    url: "/about/"
  - name: "Languages"
    dropdown: "langs"

dropdown_menus:
  - id: "langs"
    links:
      - name: "日本語"
        url: "/"
      - name: "English"
        url: "/en/"


home_cards:
  - image: "/assets/images/a-close-up-of-black-microphone.jpg"
    img_alt: "A Close Up Of Black Microphone Photo by Thom Bradley on Burst by Shopify"
    heading: "Hey"
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
    button_text: "Read more"
    button_url: "/"
  - image: "/assets/images/entrepreneurs-journal.jpg"
    img_alt: "Entrepreneurs Journal Photo by Matthew Henry on Burst by Shopify"
    heading: "Hey"
    description: "Lorem ipsum dolor sit amet."
    button_text: "Read more"
    button_url: "/"
  - image: "/assets/images/laptop-on-desk.jpg"
    img_alt: "Laptop On Desk Photo by Matthew Henry on Burst by Shopify"
    heading: "Hey"
    description: "Lorem ipsum dolor sit amet."
    button_text: "Read more"

# Footer data
copyright: "Lukion LLC" # Copyright notice
footer_description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."

footer_nav:
  - heading: "Our Products"
    navigations:
      - name: "Web application"
        url: "/"
      - name: "Website"
        url: "/"
      - name: "Loop"
        url: "/"
  - heading: "Legal"
    navigations:
      - name: "Company Info"
        url: "/"
      - name: "Privacy Notice"
        url: "/"


# About page
ceo_message_title: "会社代表挨拶"
ceo_message: >
  Lorem ipsum dolor sit amet, consectetur adipiscing elit, 
  sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 
  Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris 
  nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in 
  reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla 
  pariatur. Excepteur sint occaecat cupidatat non proident, 
  sunt in culpa qui officia deserunt mollit anim id est laborum.
ceo_name: "代表取締役 山田太郎"
ceo_photo: /assets/images/light-and-backdrop-photography.jpg
ceo_photo_alt: "Light and Backdrop Photography Photo by Matthew Henry on Burst by Shopify"


company_info_title: "会社概要"
company:
  - heading: "法人番号"
    data:
      - "0000000000000"
  - heading: "会社名"
    data:
      - "ABC株式会社"
  - heading: "代表者"
    data:
      - "山田 太郎"
  - heading: "所在地"
    data:
      - "東京都千代田区1-1-1"
  - heading: "資本金"
    data:
      - "100万円"
  - heading: "事業内容"
    data:
      - "ITコンサルティング事業"
      - "ソフトウェア開発事業"
      - "プロモーション・コンテンツ企画制作事業"
  - heading: "設立"
    data:
      - "1999年9月"
  - heading: "従業員数"
    data:
      - "8名"
  - heading: "主な取引先"
    data:
      - "D株式会社"
      - "合同会社E"
      - "有限会社F"
  - heading: "主な取引銀行"
    data:
      - "G銀行（本店）"
      - "H銀行（I支店）"

# Include custom directories and files
include:
  - _pages/

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
